candle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('world/', include('world.urls')),
    path('',include('players.urls')),
    path('forum/',include('forum.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

forum/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('post/new',views.make_post, name = 'newpost'),
    path('post/<int:pk>',views.view_post, name = 'showpost'),
    path('post/<int:pk>/reply',views.make_reply, name = 'reply'),
    path('categories',views.Categories.as_view(),name = 'cats'),
    path('category/<int:pk>', views.category, name = 'cat'),
]

players/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path('',views.home,name='home'),
    path('accounts/signup/',views.signup, name = 'signup'),
    path('accounts/activate/<uid>/<token>',views.activate,name = 'activate'),
    path('accounts/activationsent/',views.asnt,name = 'activation_sent'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/profile/', views.profile, name = 'profile'),
    path('accounts/<int:pk>/', views.PlayerPage.as_view(), name = 'player_page'),
    path('accounts/reset_token/',views.reset_token, name = 'reset_token'),
    path('characters/<int:charid>', views.char_profile, name = 'char_profile'),
    path('characters/<int:charid>/rename/', views.request_rename, name = 'char_rename'),
    path('characters/<int:charid>/projects/', views.char_projects, name = 'char_projects'),
    path('characters/makeimage/',views.char_image,name = 'char_image'),
    path('characters/change/',views.PickChar.as_view(), name = 'char_change'),
    path('characters/new/',views.MakeChar.as_view(), name = 'char_new'),
    path('characters/renames/',views.Renames.as_view(), name = 'char_renames'),
    path('characters/renames/<int:pk>/',views.RenameDetail.as_view(), name = 'char_renames_details'),
    path('characters/renames/<int:id>/approve/',views.rename_approve, name = 'char_renames_approve'),
    path('characters/renames/<int:id>/reject/',views.rename_reject, name = 'char_renames_reject'),
    path('characters/<int:charid>/api/getinfo/', views.get_char_info, name = 'char_api_info'),
    path('projects/api/relocate', views.start_relocate, name = 'projects_api_relocate'),
    path('projects/api/cellprojects',views.get_projects_for_cell, name = 'projects_api_cell'),
    path('projects/api/start_character_project',views.start_character_project, name = 'projects_api_start_char'),
    path('projects/api/start_cell_project',views.start_cell_project, name = 'projects_api_start_cell'),
    path('projects/api/restart',views.start_project, name = 'projects_api_restart'),
    path('projects/api/stop',views.stop_project, name = 'projects_api_stop'),
    path('projects/api/set_priority',views.set_project_priority, name = 'projects_api_set_priority'),
    path('projects/popup', views.ProjectPopupView.as_view(), name='project_popup')
    ]

players/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
# Create your models here.

import json

from .managers import CustomUserManager
from world.constants import POP_RACE
from world.strings import month_names
from world.logic import get_active_world
from world.models import Faction, Pop, PopTag, World
from .constants import GENDER, UNIQUE_TAGS, CHAR_TAG_NAMES, PROJECTS, EXP_TO_TAG, EXP_TO_HUMAN


from django.utils.text import format_lazy
from django.utils.translation import pgettext_lazy

class Player(AbstractUser):
    total_score = models.IntegerField(default = 0)
    score = models.IntegerField(default = 0)
    high_score = models.IntegerField(default = 0)

    objects=CustomUserManager()
    bloodline_traits = models.ManyToManyField('Trait', blank = True)
    @property
    def current_char(self):
        from .logic import PCUtils
        return PCUtils.get_current_char(self)
    @property
    def bloodline_chars(self):
        return Character.objects.filter(
            tags__content = f'{self.id}',
            tags__name = CHAR_TAG_NAMES.BLOODLINE
        )


    def level(self, subject):
        try:
            t = self.bloodline_traits.get(name__startswith = f'exp.{subject}')
            lvl = int(t.name.strip(f'exp.{subject}'))
            return lvl
        except Trait.DoesNotExist:
            return 0



class RenameRequest(models.Model):
    new_name = models.CharField(max_length = 100)
    character = models.ForeignKey('Character', on_delete=models.CASCADE)
    player = models.ForeignKey('Player', on_delete=models.CASCADE)
    def approve(self):
        self.character.name = self.new_name
        self.character.save()
        self.delete()
    def reject(self):
        self.delete()


class Character(models.Model):
    name = models.CharField(max_length = 100)
    birth_date = models.IntegerField()
    primary_race = models.CharField(
        choices = POP_RACE.choices,
        max_length = 3
    )
    secondary_race = models.CharField(
        choices = POP_RACE.choices,
        max_length = 3
    )
    gender = models.CharField(
        choices = GENDER.choices,
        max_length = 1
    )

    @property
    def world(self):
        try:
            tag = self.tags.get(name=CHAR_TAG_NAMES.WORLD)
            if tag.content=='':
                tag.content=str(get_active_world().id)
                tag.save()
        except CharTag.DoesNotExist:
            tag = self.tags.create(name=CHAR_TAG_NAMES.WORLD,
                                   content=str(get_active_world().id))
            tag.save()
        finally:
            return World.objects.get(id=int(tag.content))

    @world.setter
    def world(self,world):
        tag, _ = self.tags.get_or_create(name=CHAR_TAG_NAMES.WORLD)
        tag.content = str(world.id)

    @property
    def birth_date_human_readable(self):
        if self.birth_date>=0:
            months = (self.birth_date % 12)
            years = self.birth_date // 12
        else:
            months = 11 - (self.birth_date%12)
            years = self.birth_date//12
        return format_lazy( '{born}: {years}, {month}',
        years=years, month = month_names[months],
        born = pgettext_lazy(self.gender,"родился").capitalize())

    @property
    def death_human_readable(self):
        if self.death is None:
            return None
        if self.death>=0:
            months = (self.death % 12)
            years = self.death // 12
        else:
            months = 11 - (self.death%12)
            years = self.death//12
        return format_lazy( '{born}: {years}, {month}',
        years=years, month = month_names[months],
        born = pgettext_lazy(self.gender,"умер").capitalize())

    @property
    def race_human_readable(self):
        return pgettext_lazy(f'char-{self.gender}-{self.secondary_race}',self.primary_race)

    @property
    def location(self):
        try:
            tag = self.tags.get(name = CHAR_TAG_NAMES.LOCATION)
            return json.loads(tag.content)
        except CharTag.DoesNotExist:
            return None

    @location.setter
    def location(self, cell):
        tag, _ = self.tags.get_or_create(name = CHAR_TAG_NAMES.LOCATION)
        class Dummy: #Поддержка словаря
            def __init__(self, d):
                self.x = d['x']
                self.y = d['y']
        if isinstance(cell, dict):
            cell = Dummy(cell)
        tag.content = f'{{"x":{cell.x}, "y":{cell.y} }}'
        tag.save()

    @property
    def controller(self):
        try:
            tag = self.tags.get(name = CHAR_TAG_NAMES.CONTROLLED)
            return Player.objects.get(id = int(tag.content))
        except CharTag.DoesNotExist:
            return None

    @property
    def bloodlines(self):
        tags = self.tags.filter(name = CHAR_TAG_NAMES.BLOODLINE)
        ids = map(lambda t: int(t.content), tags)
        return Player.objects.filter(pk__in = ids)

    @property
    def clothes(self):
        try:
            return self.tags.get(name = CHAR_TAG_NAMES.CLOTHES).content
        except CharTag.DoesNotExist:
            return "stone_age"
    #PROJECTS AND EXP
    @property
    def active_projects(self):
        return self.projects.filter(is_active=True)
    @property
    def current_project(self):
        try:
            return self.active_projects.get(is_current=True)
        except Project.DoesNotExist:
            return None

    def start_next_project(self):
        try:
            first = self.active_projects.exclude(is_current=True).first()
            if first is None:
                return
            first.is_current = True
            first.save();
        except Project.DoesNotExist:
            pass

    @property
    def educated(self):
        return self.traits.filter(name__startswith = 'exp.').exists()

    def level(self, subject):
        try:
            t = self.traits.get(name__startswith = f'exp.{subject}')
            lvl = int(t.name.strip(f'exp.{subject}'))
            return lvl
        except Trait.DoesNotExist:
            return 0

    def bloodline_level(self, subject):
        if self.bloodlines.count()==0:
            return 0
        lvl = 0
        for bl in self.bloodlines:
            lvl = max(lvl, bl.level(subject))
        return lvl

    def get_exp(self, subject):
        tname = EXP_TO_TAG[subject]
        try:
            tag = self.tags.get(name=tname)
            return int(tag.content)
        except CharTag.DoesNotExist:
            return 0

    def set_exp(self, subject, exp :int):
        tname = EXP_TO_TAG[subject]
        tag, _ = self.tags.get_or_create(name=tname)

        try:
            tag.content = f'{int(exp)}'
            tag.save()
        except ValueError:
            pass

    def level_up(self, subject):
        lvl = self.level(subject)
        if lvl>0:
            old_trait = self.traits.get(name = f'exp.{subject}{lvl}')
            self.traits.remove(old_trait)
        lvl+=1
        try:
            new_trait = Trait.objects.get(name = f'exp.{subject}{lvl}')
            self.traits.add(new_trait)
        except Trait.DoesNotExist:
            pass


    #--------------------------------------------
    #RELATIONS
    @property
    def friends(self):
        tags = self.tags.filter(name = CHAR_TAG_NAMES.FRIEND_WITH)
        ids = map(lambda t: int(t.content), tags)
        one_side = Character.objects.filter(pk__in = ids)
        other_side = Character.objects.filter(
            tags__content = f'{self.id}',
            tags__name = CHAR_TAG_NAMES.FRIEND_WITH
        )
        pre = one_side | other_side
        return pre.distinct()

    def add_friendship(self, other):
        other_exists = other.tags.filter(
            content = f'{self.id}',
            name = CHAR_TAG_NAMES.FRIEND_WITH
        ).exists()
        this_exists = self.tags.filter(
            content = f'{other.id}',
            name = CHAR_TAG_NAMES.FRIEND_WITH
        ).exists()
        if other_exists or this_exists:
            return
        CharTag(
            character = self,
            name = CHAR_TAG_NAMES.FRIEND_WITH,
            content = f'{other.id}'
        ).save()

    def remove_friendship(self, other): # :(
        try:
            t = other.tags.get(
                content = f'{self.id}',
                name = CHAR_TAG_NAMES.FRIEND_WITH
            )
            t.delete()
        except CharTag.DoesNotExist:
            pass
        try:
            t = self.tags.get(
            content = f'{other.id}',
            name = CHAR_TAG_NAMES.FRIEND_WITH
            )
            t.delete()
        except CharTag.DoesNotExist:
            pass

    def is_friend_of(self, other):
        if self.tags.filter(
            content = f'{other.id}',
            name = CHAR_TAG_NAMES.FRIEND_WITH
            ).exists():
            return True
        if other.tags.filter(
            content = f'{self.id}',
            name = CHAR_TAG_NAMES.FRIEND_WITH
            ).exists():
            return True
        return False

    @property
    def enemies(self):
        tags = self.tags.filter(name = CHAR_TAG_NAMES.ENEMY_OF)
        ids = map(lambda t: int(t.content), tags)
        one_side = Character.objects.filter(pk__in = ids)
        other_side = Character.objects.filter(
            tags__content = f'{self.id}',
            tags__name = CHAR_TAG_NAMES.ENEMY_OF
        )
        pre = one_side | other_side
        return pre.distinct()

    def add_enmity(self, other):
        other_exists = other.tags.filter(
            content = f'{self.id}',
            name = CHAR_TAG_NAMES.ENEMY_OF
        ).exists()
        this_exists = self.tags.filter(
            content = f'{other.id}',
            name = CHAR_TAG_NAMES.ENEMY_OF
        ).exists()
        if other_exists or this_exists:
            return
        CharTag(
            character = self,

players/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError
from .models import Player, Character
from .logic import PCUtils
from .constants import PROJECTS as p
from .constants import ALLOWED_EXP_CHOICES
from world.models import Cell
from world.constants import CITY_TYPE

class MultipleValueWidget(forms.TextInput):
    def value_from_datadict(self, data, files, name):
        return data.getlist(name)

class MultipleValueField(forms.Field):
    widget = MultipleValueWidget


def clean_char_id(x):
    try:
        Character.objects.get(id = int(x))
    except ValueError:
        raise ValidationError("Неверный id: {}".format(repr(x)))
    except Character.DoesNotExist:
        raise ValidationError("Персонаж не найден: {}".format(repr(x)))


class MultipleCharIdField(MultipleValueField):
    def clean(self, value):
        return [clean_char_id(x) for x in value]


ProjectForms= dict()

def project_form(project_type):
    def decorator(func):
        ProjectForms[project_type] = func
        return func
    return decorator

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = Player
        fields = ('username', 'email', 'password1', 'password2')

class CharPickForm(forms.Form):
    charpick = forms.ModelChoiceField(
        queryset=Character.objects.none(),
        label = _("Pick Character"),
        widget=forms.RadioSelect
    )

    def __init__(self, player, *args, **kwargs):
        super(CharPickForm, self).__init__(*args, **kwargs)
        self.fields['charpick'].queryset = PCUtils.get_available_chars(player)

@project_form(p.TYPES.RELOCATE)
class ProjectRelocateForm(forms.Form):
    x = forms.IntegerField(min_value = 0)
    y = forms.IntegerField(min_value = 0)


@project_form(p.TYPES.STUDY)
class ProjectStudyForm(forms.Form):
    subject = forms.ChoiceField(choices = ALLOWED_EXP_CHOICES)
    teacher =  forms.IntegerField(required = False)


@project_form(p.TYPES.TEACH)
class ProjectTeachForm(forms.Form):
    subject = forms.ChoiceField(choices = ALLOWED_EXP_CHOICES)
    pupils = MultipleCharIdField()

@project_form(p.TYPES.MAKE_FRIEND)
class ProjectFriendForm(forms.Form):
    pass

@project_form(p.TYPES.BUILD_TILE)
class BuildForm(forms.Form):
    city_type = forms.ChoiceField(choices=CITY_TYPE.choices)
    with_pop = forms.ModelChoiceField(
        queryset=Character.objects.none(),
        label = _("Pick Pop"),
        widget=forms.RadioSelect
    )

    def __init__(self, player, *args, **kwargs):
        super(BuildForm, self).__init__(*args, **kwargs)
        character = player.current_char
        loc = character.location
        self.fields['with_pop'].queryset = Cell.objects.get(x=loc['x'],y=loc['y']).pop_set.all()

@project_form(p.TYPES.FORTIFY_CITY)
class FortifyForm(forms.Form):
    with_pop = forms.ModelChoiceField(
        queryset=Character.objects.none(),
        label = _("Pick Pop"),
        widget=forms.RadioSelect
    )

    def __init__(self, player, *args, **kwargs):
        super(FortifyForm, self).__init__(*args, **kwargs)
        character = player.current_char
        loc = character.location
        self.fields['with_pop'].queryset = Cell.objects.get(x=loc['x'],y=loc['y']).pop_set.all()

players/templates/account_activation_email.html
{% load i18n %}
{% blocktrans %}
Приветствую, {{user.username}}!

Кто-то пытался зарегистрироваться на World of Candle, используя эту почту.
Если это были не вы, просто проигнорируйте это письмо. Для завершения регистрации используйте ссылку ниже:

{% endblocktrans %}
http://{{ domain }}{% url 'activate' uid=uid token=token %}

players/templates/account_activation_invalid.html
{% extends "base.html" %}
{% load i18n %}
{%block content%}
{% trans "Извините, эта ссылка недействительна." %}

{% endblock %}

players/templates/account_activation_sent.html
{% extends "base.html" %}
{% load i18n %}
{%block content%}
{% trans "Для завершения регистрации используйте ссылку, отправленную на указанную почту." %}

{% endblock %}

players/templates/char_maker_template.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block addhead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/charmaker.css' %}" />
{% endblock %}

{% block content %}
    {% if err %}<p>{{err}}</p>{% endif %}

    {% for race in ALLOWED_RACES %}
        <a onclick = "race_pick(this,'{{race}}','f')"><img src="/characters/makeimage/?gender=f&race={{race}}&clothes=stone_age"></a>
        <a onclick = "race_pick(this,'{{race}}','m')"><img src="/characters/makeimage/?gender=m&race={{race}}&clothes=stone_age"></a>
    {% endfor %}
    <p><strong id="race_name"></strong></p>
    <p id="race_desc"></p>
    <a onclick = "spec_pick(this,'politics')"><img src="{% static 'characters/politics_big.png' %}"></a>
    <a onclick = "spec_pick(this,'military')"><img src="{% static 'characters/military_big.png' %}"></a>
    <a onclick = "spec_pick(this,'economics')"><img src="{% static 'characters/economics_big.png' %}"></a>
    <a onclick = "spec_pick(this,'science')"><img src="{% static 'characters/science_big.png' %}"></a>
    <p><strong id="spec_name"></strong></p>
    <p id="spec_desc"></p>
    <form action="#" method="post" onsubmit="return yesno()">
        {% csrf_token %}
        <input type="hidden" name = "gender" id="char_gender">
        <input type="hidden" name = "race" id="char_race">
        <input type="hidden" name = "exp" id="char_exp">
        <label for="cname">Имя персонажа (сначала проходит модерацию)</label>
        <input name ="name" id="char_name">
        <input type = "hidden" value = "{% trans 'Создать персонажа' %}" id="confirm">
    </form>
    <script src = "{% static 'characters/charmaker.js' %}"></script>

{% endblock %}

f"<a onclick = \"race_pick(\'{r}\',\'{g}\')\"><img src=\"/characters/makeimage/?gender={g}&race={r}&clothes=stone_age\"></a>"

players/templates/char_project_template.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load player_tags %}


{% block content %}
    <input type="hidden" id="auth" value="{{token}}">
    <script src = "{% static 'characters/projects.js' %}"></script>
    <h2><a href="{% url 'char_profile' charid=character.id %}">{{character.name}}</a>, {{character.race_human_readable}}</h2>

    <section  class="border">
    <p><img src="{% url 'char_image' %}?gender={{character.gender}}&race={{character.primary_race}}&clothes={{character.clothes}}"></img></p>
    {% if character.controller%}
        <p>Этот персонаж находится под контролем игрока <a href="{% url 'player_page' pk=character.controller.id %}">
            {{character.controller.username}}</a>
        </p>
    {% endif %}
    {% if character.location %}
        <p>Местонахождение: {{character.location.x}}x{{character.location.y}}</p>
    {% endif %}
    </section>

    <section class="border">
        <h3>{% trans "Проекты" %}</h3>
        {% if character == current_char %}
        <table class="border">
            {% for project in character.projects.all %}
            {% with prev=character.projects.all|previous:forloop.counter0 next=character.projects.all|next:forloop.counter0%}
            {% if not project.is_current %}
            <tr>
                <td>{{project.human_readable}}</td>
                <td>{{project.percent_ready}}</td>
                <td><a href="#" onclick=restart_project({{project.id}})>{% trans 'Вернуться к проекту' %}</a></td>
                <td class="border">{% if prev and not prev.is_current %}<a href="#" onclick="setqueue({{project.id}},{{prev.priority|add:-1}})">/\</a>{% else %}_{% endif %}</td>
                <td class="border">{% if next and not next.is_current %}<a href="#" onclick="setqueue({{project.id}},{{next.priority|add:1}})">\/</a>{% else %}_{% endif %}</td>
                <td><a href="#" onclick=stop_project({{project.id}})>{% trans 'Забросить проект' %}</a></td>
            </tr>
            {% endif %}
            {% endwith %}
            {% endfor %}
        </table>

        {% endif %}
        {% for form in forms %}
        <strong>{{form.type.label}}</strong>
        <form onclick=register_form({{character.id}},"{{form.type}}",this)>
            {{form.form}}
            <input type="submit" value="Начать проект">
        </form>
        {% endfor %}
    </section>



{% endblock %}

players/templates/char_template.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load player_tags %}


{% block content %}
    <input type="hidden" id="auth" value="{{token}}">
    <script src = "{% static 'characters/projects.js' %}"></script>
    <h2>{{character.name}}, {{character.race_human_readable}}</h2>
    <aside class="border">
        <h3>{% trans 'Отношения' %}</h3>
        <h4>{% trans 'Друзья' %}</h4>
        <table class ="reltable">
            {% for friend in character.friends.all %}
                <tr>
                    <td class="border"><img src="{% url 'char_image' %}?gender={{friend.gender}}&race={{friend.primary_race}}&clothes={{friend.clothes}}"></img></td>
                    <td class="border"><a href="{% url 'char_profile' charid=friend.id %}">{{friend.name}}</a></td>
                </tr>
            {% endfor %}
        </table>
        <h4>{% trans 'Враги' %}</h4>
        <table class ="reltable">
            {% for enemy in character.enemies.all %}
                <tr>
                    <td class="border"><img src="{% url 'char_image' %}?gender={{enemy.gender}}&race={{enemy.primary_race}}&clothes={{enemy.clothes}}"></img></td>
                    <td class="border"><a href="{% url 'char_profile' charid=enemy.id %}">{{enemy.name}}</a></td>
                </tr>
            {% endfor %}
        </table>
        <h4>{% trans 'Родители' %}</h4>
        <table class ="reltable">
            {% for parent in character.parents.all %}
                <tr>
                    <td class="border"><img src="{% url 'char_image' %}?gender={{parent.gender}}&race={{parent.primary_race}}&clothes={{parent.clothes}}"></img></td>
                    <td class="border"><a href="{% url 'char_profile' charid=parent.id %}">{{parent.name}}</a></td>
                </tr>
            {% endfor %}
        </table>
        <h4>{% trans 'Дети' %}</h4>
        <table class ="reltable">
            {% for child in character.children.all %}
                <tr>
                    <td class="border"><img src="{% url 'char_image' %}?gender={{child.gender}}&race={{child.primary_race}}&clothes={{child.clothes}}"></img></td>
                    <td class="border"><a href="{% url 'char_profile' charid=child.id %}">{{child.name}}</a></td>
                </tr>
            {% endfor %}
        </table>
    </aside>

    <section  class="border">
        <p>{{character.birth_date_human_readable}} {% if character.death %} - {{character.death_human_readable}} {% endif %}</p>
    <p><img src="{% url 'char_image' %}?gender={{character.gender}}&race={{character.primary_race}}&clothes={{character.clothes}}"></img></p>
    {% if character.controller%}
        <p>Этот персонаж находится под контролем игрока <a href="{% url 'player_page' pk=character.controller.id %}">
            {{character.controller.username}}</a>
        </p>
    {% endif %}
    {% if character.location %}
        <p>Местонахождение: {{character.location.x}}x{{character.location.y}}</p>
    {% endif %}
    </section>

    <aside class="border">
        <h3>{% trans 'Династии' %}</h3>
        <table>
            {% for bl in character.bloodlines.all %}
            <tr>
                <td class="border"><!-- TODO: Bloodline crest --></td>
                <td class="border"><a href="{% url 'player_page' pk=bl.id %}">{{bl.username}}</a> </td>
            </tr>

            {% endfor %}
        </table>
    </aside>

    <section class="border">
        <h3>{% trans "Проекты" %}</h3>
        {% if character.current_project %}
        <p>{% trans "Текущий проект" %}: {{character.current_project.human_readable}} ({{character.current_project.percent_ready}})</p>
        {% endif %}
        {% if character == current_char %}
        <table class="border">
            {% for project in character.active_projects %}
            {% with prev=character.projects.all|previous:forloop.counter0 next=character.projects.all|next:forloop.counter0%}
            {% if not project.is_current %}
            <tr>
                <td>{{project.human_readable}}</td>
                <td>{{project.percent_ready}}</td>
                <td><a href="#" onclick=restart_project({{project.id}})>{% trans 'Вернуться к проекту' %}</a></td>
                <td class="border">{% if prev and not prev.is_current %}<a href="#" onclick="setqueue({{project.id}},{{prev.priority|add:-1}})">/\</a>{% else %}_{% endif %}</td>
                <td class="border">{% if next and not next.is_current %}<a href="#" onclick="setqueue({{project.id}},{{next.priority|add:1}})">\/</a>{% else %}_{% endif %}</td>
                <td><a href="#" onclick=stop_project({{project.id}})>{% trans 'Забросить проект' %}</a></td>
            </tr>
            {% endif %}
            {% endwith %}
            {% endfor %}
        </table>

        {% endif %}
        <a href="{% url 'char_projects' charid=character.id %}">Начать проект</a>
    </section>
    <section class="border">
        <h3>{% trans "Черты" %}</h3>
        <table>
        {% for trait in character.traits.all %}
           <tr><td class="border">{% if trait.image %}<img src="{{ MEDIA_URL }}{{trait.image}}"></img>{% endif %}</td><td class="border">{{trait.verbose_name}}</td></tr>
        {% endfor %}
        </table>
    </section>

     {% if character == current_char %}
    <section class="border">
        <form action="{% url 'char_rename' charid=character.id %}" method="post">
        {% csrf_token %}
        <input name="name">
        <input type="submit" value="{% trans 'Запросить переименование' %}">
    </form>
    </section>

    {% endif %}

    {% if character == current_char or user.is_staff %}
    <section class="border">
        <p>Рассматириваются запросы:</p>
        <ul>
            {% for rename in character.renamerequest_set.all %}
            <li><a href="{% url 'char_renames_details' pk=rename.id %}">#{{rename.id}}</a> {{rename.new_name}}</li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}


{% endblock %}

players/templates/custom_interface.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Основные" %}</h2>
<label for="back-color">{% trans "Цвет фона" %}</label>
<input type="color" id="back-color">
<label for="text-color">{% trans "Цвет текста" %}</label>
<input type="color" id="text-color">
<h2>{% trans "Верхнее меню" %</h2>
<label for="back-color-menu">{% trans "Цвет фона" %}</label>
<input type="color" id="back-color-menu">
<label for="text-color-menu">{% trans "Цвет текста" %}</label>
<input type="color" id="text-color-menu">
{% endblock %}

players/templates/pick_new_char.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% if process_error%}
<p>{{process_error}}</p>
{% endif %}
{{ form.non_field_errors }}
<form action="{% url 'char_change' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="{% trans 'Выбрать персонажа' %}">
</form>
{% endblock %}

players/templates/project_popup_succcess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Проект запущен</title>
</head>
<body>
<h1>Успех!</h1>
<p>Вы можете закрыть это окно</p>
</body>
</html>